DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS user;


CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  community TEXT NOT NULL,
  text TEXT NOT NULL,
  Username TEXT NOT NULL,
  url TEXT,
  dt DATETIME NOT NULL,
  upvotes INTEGER NOT NULL,
  downvotes INTEGER NOT NULL
);


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  karma INTEGER NOT NULL
);
