name: Audit

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  audit:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Scanning source code for vulnerabilities
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck -json ./...

    - name: Security Scan
      uses: securego/gosec@master
      with:
        args: ./...
