name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Prep
      run: |
        go version
        go mod tidy

    - name: Test
      run: go test -v ./tests/*

    - name: Code Coverage
      run: go test ./tests/... -race -coverprofile=cover.out -coverpkg ./...

    - name: Upload data to Codecov
      uses: codecov/codecov-action@v3
